---
title: "p8105_hw1_xh2395"
author: "Xin  He"
date: "9/14/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  problem 1

```{r}
library(tidyverse)

hw1_df = tibble(
  vec_numeric = rnorm(8, mean = 0, sd = 1),
  vec_logical = vec_numeric > 0,
  vec_char = character(length = 8),
  vec_factor = factor(vec_char, levels = c("a", "b", "c"))
)

mean(pull(hw1_df, vec_numeric))
mean(pull(hw1_df, vec_logical))
mean(pull(hw1_df, vec_char))
mean(pull(hw1_df, vec_factor))

as.numeric(pull(hw1_df, vec_logical))
as.numeric(pull(hw1_df, vec_char))
as.numeric(pull(hw1_df, vec_factor))

as.numeric(pull(hw1_df, vec_logical))*pull(hw1_df, vec_numeric)
as.factor(pull(hw1_df, vec_logical))*pull(hw1_df, vec_numeric)
as.numeric(as.factor(pull(hw1_df, vec_logical)))*pull(hw1_df, vec_numeric)
```

## problem 2
```{r}
problem2_df = tibble(
  x = rnorm(500, mean = 0, sd = 1),
  y = rnorm(500, mean = 0, sd = 1),
  vec_logical = x + y > 1,
  vec_numeric = as.numeric(vec_logical),
  vec_factor = as.factor(vec_logical)
)
```

The size of the dataset is `r nrow(problem2_df)` and `r ncol(problem2_df)`,

The mean of x is `r mean(pull(problem2_df, x))`,

The median of x is`r median(pull(problem2_df, x))`,

The standard deviation of x is `r sd(pull(problem2_df, x))`,

The proportion of cases for which x + y > 1 is `r mean(pull(problem2_df, vec_logical))`.

```{r}
ggplot(problem2_df, aes(x = x, y = y, color = vec_logical)) + geom_point()
ggsave("firstplot.png")
ggplot(problem2_df, aes(x = x, y = y, color = vec_numeric)) + geom_point()
ggplot(problem2_df, aes(x = x, y = y, color = vec_factor)) + geom_point()


```



